name: Conda CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up environment using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          auto-activate-base: false

      - name: Test if essential Python packages are working
        run: |
          python -c "import numpy, pandas, sklearn; print('Environment is working!')"
