name: Conda CI

on: [push, pull_request]  # Triggers on push/PR

jobs:
  test-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: stat-learn-env
          auto-activate-base: false

      - name: Verify installations
        shell: bash -l {0}  # Ensures Conda is activated
        run: |
          python -c "import numpy; print(f'NumPy {numpy.__version__}')"
          python -c "import pandas; print(f'pandas {pandas.__version__}')"
          python -c "import sklearn; print(f'scikit-learn {sklearn.__version__}')"
